# Generated by Django 6.1 on 2026-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriguardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
