# Generated by Django 6.1 on 2026-08-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriguardapp', '0002_logintable_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='email',
            new_name='username',
        ),
    ]
